Title: Introduction to Statistical Learning
Date: 2017-01-01
Tags: data-science, learning, statistics
Category: tech
Slug: islr
Summary: *An Introduction to Statistical Learning with Applications in R* is a popular textbook covering basic statistical learning techniques (classification, regression, cross-validation, etc.) as well as their application in R.

*An Introduction to Statistical Learning with Applications in R*, or just ISLR, is an accessible and frequently used introductory textbook for the basics of statistical learning. While machine learning is concerned more with pure prediction, statistical learning emphasizes estimation methods and valid inference. These two fields are less black and white differences and more shades of gray.



# Prereq

At least one course in statistics is needed. A second course that specializes in regression would also go a long way (particularly for those who are self teaching).

Calculus is mostly avoided and linear algebra is kept to a minimum. Of course, a "just algebra" approach can get fairly complicated when dealing with Bayesian manipulations (this is particularly true during the section on linear discriminant analysis).

# Contents

Below is a basic table of contents with select topics. Each chapter has an R lab applying the ideas covered as well as exercises.

1. Introduction
2. Statistical Learning
    * Assessing Model Accuracy
    * Bias-Variance Trade-off
3. Linear Regression
    * Simple and Multiple Linear Regression
    * Qualitative Predictors
    * Assessing Model Accuracy
4. Classification
    * Logistic Regression
    * Linear Discriminant Analysis
5. Resampling Methods
    * Cross-Validation
    * Bootstrap
6. Linear Model Selection and Regularization
    * Subset Selection
    * Shrinkage Methods
    * Dimension Reduction Methods
7. Moving Beyond Linearity
    * Polynomial Regression
    * Splines
8. Tree-Based Methods
    * Decision Trees
    * Bagging, Random Forests, Boosting
9. Support Vector Machines
10. Unsupervised Learning
    * PCA
    * Clustering Methods

# Resources

One reason why the ISLR is so popular is because it's free! You can download the book and lab code [here](http://www-bcf.usc.edu/~gareth/ISL/).

Lectures from the authors of the book can be viewed [here](http://www.dataschool.io/15-hours-of-expert-machine-learning-videos/). I highly recommend these videos. It definitely took my data analysis to the next level.

Currently I am compiling my own notes/outline of the book, which can be found on [github](https://github.com/tkthomas27/ISL-Notes).
