---
title: "Notebooks"
---

---

# Shiny Apps

[Financial Scatter Plots](https://kylethomas.shinyapps.io/finance_app/)

Shiny app for comparing financial ratios and metrics. Allows to filter by year, market capitalization, S&P500 membership, share codes, industry and outliers. Dynamically displays scatter plot, distribution of variables being compared, as well as a fitted line with linear equation, $R^2$, and number of observations.

---

[Weather Comparison](https://kylethomas.shinyapps.io/weather_comp/)

Shiny app for comparing climate data between two cities. Shows records highs/lows, average highs/lows, precipitation, sunshine hours, and geographic position. Scales are dynamically adjusted to be the same when comparing cities.

---

# R Notebooks

---

[Climate Data](weather_tables.html)

Run down on how I scraped data from wikipedia and prepared it for use in [Weather Comparison](https://kylethomas.shinyapps.io/weather_comp/) app. 

---

[Getting Data from CRSP](crsp_gettingdata.html)

There are multiple ways of getting data from WRDS. In this notebook, we will go over two primary ways as well as their respective pros and cons. We'll also go over how to upload the data into a PostgreSQL database for easier use with your data analysis package of choice.

---

[GGPairs](ggpairs.html)

In this notebook we walk through the R package `ggpairs` and how it can help us quickly visualize the relationship between variables.

---

# Python Notebooks

---

[Getting Started with NFLDB and Postgresql](nfldb-postgresql.html)

NFLDB and PostgreSQL are powerful yet easy to use tools for querying NFL data. This workflow can be used to answer questions you might have regarding the NFL or building a predictive model.

---

[NFL Prediction with Logistic Regression](nfl-prediction-1.html)

The NFL season is upon us. Most pundits can barely pick over 50% of the games right. Can we use machine learning techniques to beat them? Using a PostgreSQL database, we can build statistical tables that fed into a logistic regression model to predict home team wins. We also strengthen our model using ridge regression, scaling, and cross validation.

---

[Supply Demand Basic](supply-demand-basics.html)

Supply and demand are fundamental building blocks to understanding economics. We will review the basics of supply and demand as well as some simple (and fun) python plot building.

---

[Checkio Vol. 1](checkio-vol1.html)

checkio.org is a great place to practice your coding. In this post, we will present solutions to three of the easier challenges on checkio.

---

# Explanatory Notes

---

[Internal Rate of Return](irr.html)

A brief note walking the formulas of the time value of money and the computation of the internal rate of return.

---

[Command Line](cli_basics.html)

A quick cheatsheet to getting started with the command line on MacOS.

---

[macOS Package Management](macOS_package_management.html)

Whether you are adding functionality to your base OS or expanding the capabilities of R or Python, effectively managing your packages is an essential task for any data scientist.

---

[Chain of Thought: Norm](cot_norm.html)

A chain of thought regarding the mathematical concept of norm.

---

[Note Melody Music](note-melody-music.html)

A meditation on Buddhaghosa and the phrase 'evam me sutam'.

---
