---
title: "Note, Melody, Music"
author: Kyle Thomas
output:
    html_document:
        toc: false
---

*The following is adapted from a paper submitted for the course "Buddhist Narrative" at Harvard Divinity School*

In the commentary on the *Mangalasuttam*, Buddhaghosa's "theory of a text" is his awareness of the various ways that meaning can be realized from a text.  One of the defining characteristics of Buddhaghosa's "theory of a text" is that meaning is the grounds for ever more meaning.  This seems to run contrary to the notion that a commentary is supposed to solve the mysteries of a text by limiting the number of possible meanings.  This notion arises from a  tension between a *knowledge* of a multiplicity of meaning and the need to *choose* from the multiplicity of meaning.  Buddhaghosa does not forego the issue of choice, but instead resolves the potential limitations of choice by demonstrating how choice can actually be the grounds for an infinitude of meaning.  This process is Buddhaghosa's "theory of a text."  By looking closely at the imbedded "theory of a text" in Buddhaghosa's commentary on *evam* *me* *sutam*, we can see how Buddhaghosa's commentary remains a lively spring of meaning even today.

Buddhaghosa selects the phrase *evam* *me* *sutam* and proceeds to realize multiple avenues of meaning that are opened up by this simple statement. This meaning-realization is forged from a tension between an intuition of more and the need to make choices.  For each root word of *evam*, me, and *sutam*, Buddhaghosa gives a list of possible meanings and then chooses which ones are to be used.   For example, *evam* can mean "simile, giving directions, praise, reproof, acceptance of a statement, mode, demonstrations, memorizing, and so on" (106).  Buddhaghosa, however, goes on to say, "Here it should be regarded as mode, as demonstration, and as memorizing" (107).  There are numerous more possible meanings ("and so on") to the word *evam*, from which Buddhaghosa chooses a particular set of meanings to work with.  This process of presentation of possibilities and choosing from among these possibilities is repeated for the words *me* and *sutam* as well.  Buddhaghosa then ties together the possible meanings of the individual words *evam*, me, and *sutam* into a series of possible meanings for the whole phrase *evam* *me* *sutam*.  However, this "whole phrase" meaning is not a final result, and is itself open up to further possible compositions of meaning.   

The three step process for a "theory of a text" then is: (1) possibility (2) choice (3) composition.  Regarding step (2), what are the criteria for Buddhaghosa to decide which meanings to use and which to not use?  Answering this question will help us better see the relationships between the infinitude of possible meanings and the specific chosen meanings given.

To help visualize Buddhaghosa's practice, we can employ a simple analogy of music composition.  Just as the root text *evam* *me* *sutam* are points on which multiple scenarios of meaning can be composed, in that same way *evam* *me* *sutam* are like the root notes of an ostinato on which melodies can be built.  *evam* *me* *sutam* continuously resounds throughout the commentary while melodies of meaning are continuously accumulated on it.  Buddhaghosa's role as a composer is to see the possible variations emerging from the root note and then compose something from them.  These variations on the root note consist of other notes that have a particular resonance with the root note.  These root note variations thus form a chord of resonant notes.

For example, Buddhaghosa sees how the term "demonstration" has a particular resonance with the root word *evam*, and from the combination of these two (i.e., *evam* as demonstration), one possible "chord of meaning" emerges.  As noted above, each root word of *evam*, me, and *sutam* has its own collection of possible "meaning chords."  After establishing a selection of these chords, Buddhaghosa then must choose which possible meanings he will keep.  This tension between possibility of meanings and the selection of meanings is critical to understanding commentarial practice and how it keeps a text open to more and more meaning.

The criteria for his choices are not concerned with which possible chords have the best or most authoritative resonance with the root text; his choices are rather concerned with how well a possible chord based on a root note resonates with a possible chord of the next root note.  To put this in terms of the commentary, his criteria for choosing a certain possible meaning of a word is based on how well it serves to make more meaning in conjunction with the other possible meanings of the other words. As a composer and commentator, Buddhaghosa is trying to make the best melodies of meaning from the root text.  The following provides an example of a melody of meaning composed by Buddhaghosa from the possible chords emerging from *evam* *me* *sutam*:

>Similarly *evam* (thus) demonstrates that the kinds of cognizance beginning with hearing have [actually] occurred in the various ways with respect to an object; *me* (by me, I) demonstrates an [individual] self; and *sutam* (heard) demonstrates an idea [cognized]. (109)

A possible meaning of *evam* is given as "demonstration."  This possible meaning of "demonstration" is then put in conjunction with other possible meanings of the words *me* ("self") and *sutam* ("idea"), and we are thus provided with a meaning for the whole phrase *evam* *me* *sutam*.   

If viewing a commentary as an authoritative, final source of meaning, then this simple melody and the other similar melodies (109) would suffice as a final meaning for the phrase *evam* *me* *sutam*.  Buddhaghosa, however, shows how this composition itself is open to new levels of possible meanings.  For example, *evam* and *me* can also have the possible meaning of "true sense and ultimate sense" and *sutam* can also possibly mean "a description [in terms] of the factual" (109).  This possible meaning can be conjoined with the above melody to make a new melody of meaning.  Buddhaghosa is thus opening up the melodies he has composed to the possibility of being the root notes for some other melody of possible meaning.  Possibility and choice give rise to more possibility and choice, ad infinitum.  Thus we can see how Buddhaghosa resolves the potentially delimiting tension of "choice" by demonstrating how "choice" can actually be the fertile grounds for more and more choice of possible meanings.  

The infinite quality, the endless possibility for words to accumulate more meaning and for notes to compose more melodies is the feature that makes Buddhaghosa's commentary a musical whole capable of producing meaning even today.  Thus, Buddhaghosa's "theory of a text" is that the possibility of meaning is an active question in perpetual need of response, and that any response is simply the grounds for potential future responses.

*All references are to:*
The Minor Readings (Khuddakapāṭha). Trans. Bhikkhu Ñānamoli. Oxford: Pali Text Society. 1991.
